FROM	golang:1.7.3 AS builder

WORKDIR /
COPY	href-counter/app.go .

RUN	go get -d -v golang.org/x/net/html \
	&& CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

CMD	["./app"]

FROM	alpine:latest
COPY	--from=builder ./app .
CMD	["./app"]
